
import type { Metadata } from 'next'
import './globals.css'
import '@radix-ui/themes/styles.css';
import { Theme } from '@radix-ui/themes';
import { inter } from './styles/fonts';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        {children}
        {/* <Theme appearance="dark" className='fullScreen'>
        </Theme> */}
      </body>
    </html>
  )
}
